# Generated by Django 2.2.2 on 2019-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='nice', max_length=150),
            preserve_default=False,
        ),
    ]
